const ropa = [
  {
    id: 1,
    name: "Botines Speedflow .4",
    price: 14999,
    img: "../img/hombre/1.jpg",
    description: "Hombre Fútbol",
    hombre: true,
    mujer: false,
    niño: false,
    populares: false,
  },
  {
    id: 2,
    name: "Buzo Selección Argentina",
    price: 12500,
    img: "../img/hombre/2.jpg",
    description: "Hombre Fútbol",
    hombre: true,
    mujer: false,
    niño: false,
    populares: true,
  },
  {
    id: 3,
    name: "Buzo Innovation Negro",
    price: 10000,
    img: "../img/hombre/3.jpg",
    description: "Hombre Casual",
    hombre: true,
    mujer: false,
    niño: false,
    populares: true,
  },
  {
    id: 4,
    name: "Buzo Negro y Blanco",
    price: 7999,
    img: "../img/hombre/4.jpg",
    description: "Hombre Casual",
    hombre: true,
    mujer: false,
    niño: false,
    populares: false,
  },
  {
    id: 5,
    name: "Camiseta Gris Oscuro",
    price: 4999,
    img: "../img/hombre/5.jpg",
    description: "Hombre Casual",
    hombre: true,
    mujer: false,
    niño: false,
    populares: false,
  },
  {
    id: 6,
    name: "Camiseta River Plate Original",
    price: 12000,
    img: "../img/hombre/6.jpg",
    description: "Hombre Fútbol",
    hombre: true,
    mujer: false,
    niño: false,
    populares: true,
  },
  {
    id: 7,
    name: "Camiseta Manchester United Original",
    price: 11199,
    img: "../img/hombre/7.jpg",
    description: "Hombre Fútbol",
    hombre: true,
    mujer: false,
    niño: false,
    populares: false,
  },
  {
    id: 8,
    name: "Zapatillas Nmd Adidas x Starwars",
    price: 32000,
    img: "../img/hombre/8.jpg",
    description: "Hombre Zapatillas",
    hombre: true,
    mujer: false,
    niño: false,
    populares: true,
  },
  {
    id: 9,
    name: "Camiseta Argentina Original",
    price: 16000,
    img: "../img/hombre/9.jpg",
    description: "Hombre Fútbol",
    hombre: true,
    mujer: false,
    niño: false,
    populares: false,
  },
  {
    id: 10,
    name: "Campera Deportiva Multicolor",
    price: 14999,
    img: "../img/hombre/10.jpg",
    description: "Hombre Running",
    hombre: true,
    mujer: false,
    niño: false,
    populares: false,
  },
  {
    id: 11,
    name: "Musculosa Negra",
    price: 5399,
    img: "../img/hombre/11.jpg",
    description: "Hombre Casual",
    hombre: true,
    mujer: false,
    niño: false,
    populares: true,
  },
  {
    id: 12,
    name: "Ojotas Blancas Innovation",
    price: 9199,
    img: "../img/hombre/12.jpg",
    description: "Hombre Casual",
    hombre: true,
    mujer: false,
    niño: false,
    populares: false,
  },
  {
    id: 13,
    name: "Remera Rosa ",
    price: 6999,
    img: "../img/hombre/13.jpg",
    description: "Hombre Casual",
    hombre: true,
    mujer: false,
    niño: false,
    populares: false,
  },
  {
    id: 14,
    name: "Remera Ladrillo ",
    price: 7499,
    img: "../img/hombre/14.jpg",
    description: "Hombre Casual",
    hombre: true,
    mujer: false,
    niño: false,
    populares: true,
  },
  {
    id: 15,
    name: "Remera Verde ",
    price: 5999,
    img: "../img/hombre/15.jpg",
    description: "Hombre Casual",
    hombre: true,
    mujer: false,
    niño: false,
    populares: false,
  },
  {
    id: 16,
    name: "Campera de Presentación River Plate ",
    price: 22000,
    img: "../img/hombre/16.jpg",
    description: "Hombre Fútbol",
    hombre: true,
    mujer: false,
    niño: false,
    populares: true,
  },
  {
    id: 17,
    name: "Short Azul",
    price: 4999,
    img: "../img/hombre/17.jpg",
    description: "Hombre Casual",
    hombre: true,
    mujer: false,
    niño: false,
    populares: false,
  },
  {
    id: 18,
    name: "Short Negro",
    price: 5499,
    img: "../img/hombre/18.jpg",
    description: "Hombre Casual",
    hombre: true,
    mujer: false,
    niño: false,
    populares: false,
  },
  {
    id: 19,
    name: "Zapatillas Stan Smith Blancas",
    price: 19999,
    img: "../img/hombre/19.jpg",
    description: "Hombre Zapatillas",
    hombre: true,
    mujer: false,
    niño: false,
    populares: true,
  },
  {
    id: 20,
    name: "Zapatillas Campus ADV",
    price: 25999,
    img: "../img/hombre/20.jpg",
    description: "Hombre Zapatillas",
    hombre: true,
    mujer: false,
    niño: false,
    populares: false,
  },

  // Sección Mujeres

  {
    id: 21,
    name: "Biker Negro Multicolor",
    price: "$6.499",
    img: ".img/mujer/21.jpg",
    description: "Mujer Running",
    hombre: false,
    mujer: true,
    niño: false,
    populares: false,
  },
  {
    id: 22,
    name: "Calza Rosa",
    price: "$7.299",
    img: ".img/mujer/22.jpg",
    description: "Mujer Casual",
    hombre: false,
    mujer: true,
    niño: false,
    populares: true,
  },

  {
    id: 23,
    name: "Calza Gris",
    price: "$7.000",
    img: ".img/mujer/23.jpg",
    description: "Mujer Casual",
    hombre: false,
    mujer: true,
    niño: false,
    populares: false,
  },
  {
    id: 24,
    name: "Campera Negra Clásica",
    price: "$12.499",
    img: ".img/mujer/24.jpg",
    description: "Mujer Casual",
    hombre: false,
    mujer: true,
    niño: false,
    populares: true,
  },
  {
    id: 25,
    name: "Buzo Essential Amarillo",
    price: "$9.999",
    img: ".img/mujer/25.jpg",
    description: "Mujer Casual",
    hombre: false,
    mujer: true,
    niño: false,
    populares: true,
  },
  {
    id: 26,
    name: "Camiseta River Plate Original",
    price: "$12.000",
    img: ".img/mujer/26.jpg",
    description: "Mujer Fútbol",
    hombre: false,
    mujer: true,
    niño: false,
    populares: true,
  },
  {
    id: 27,
    name: "Pantalón Disney Bambi",
    price: "$10.499",
    img: ".img/mujer/27.jpg",
    description: "Mujer Running",
    hombre: false,
    mujer: true,
    niño: false,
    populares: false,
  },
  {
    id: 28,
    name: "Traje de Baño Enterizo",
    price: "$8.999",
    img: ".img/mujer/28.jpg",
    description: "Mujer Natación",
    hombre: false,
    mujer: true,
    niño: false,
    populares: false,
  },
  {
    id: 29,
    name: "Zapatillas Multix Blancas",
    price: "$22.199",
    img: ".img/mujer/29.jpg",
    description: "Mujer Zapatillas",
    hombre: false,
    mujer: true,
    niño: false,
    populares: false,
  },
  {
    id: 30,
    name: "Campera de Plumas Varilite Rosa",
    price: "$32.499",
    img: ".img/mujer/30.jpg",
    description: "Mujer Casual",
    hombre: false,
    mujer: true,
    niño: false,
    populares: false,
  },
  {
    id: 31,
    name: "Top Deportivo Negro",
    price: "$4.299",
    img: ".img/mujer/31.jpg",
    description: "Mujer Running",
    hombre: false,
    mujer: true,
    niño: false,
    populares: false,
  },
  {
    id: 32,
    name: "Ojotas Blancas Innovation",
    price: "$9.199",
    img: ".img/mujer/32.jpg",
    description: "Mujer Casual",
    hombre: false,
    mujer: true,
    niño: false,
    populares: false,
  },
  {
    id: 33,
    name: "Remera Top Celeste",
    price: "$5.499",
    img: ".img/mujer/33.jpg",
    description: "Mujer Casual",
    hombre: false,
    mujer: true,
    niño: false,
    populares: false,
  },
  {
    id: 34,
    name: "Remera Negra Estampada",
    price: "$4.299",
    img: ".img/mujer/34.jpg",
    description: "Mujer Casual",
    hombre: false,
    mujer: true,
    niño: false,
    populares: false,
  },
  {
    id: 35,
    name: "Zapatillas Galaxy 5 Fucsia",
    price: "$18.899",
    img: ".img/mujer/35.jpg",
    description: "Mujer Zapatillas",
    hombre: false,
    mujer: true,
    niño: false,
    populares: false,
  },
  {
    id: 36,
    name: "Pollera Tenis Blanca ",
    price: "$5.000",
    img: ".img/mujer/36.jpg",
    description: "Mujer Tenis",
    hombre: false,
    mujer: true,
    niño: false,
    populares: false,
  },
  {
    id: 37,
    name: "Top Deportivo Rosa Oscuro",
    price: "$4.799",
    img: ".img/mujer/37.jpg",
    description: "Mujer Running",
    hombre: false,
    mujer: true,
    niño: false,
    populares: true,
  },
  {
    id: 38,
    name: "Remeron Negro",
    price: "$5.399",
    img: ".img/mujer/38.jpg",
    description: "Mujer Casual",
    hombre: false,
    mujer: true,
    niño: false,
    populares: false,
  },
  {
    id: 39,
    name: "Zapatillas Run Falcon Blancas",
    price: "$20.599",
    img: ".img/mujer/39.jpg",
    description: "Mujer Running",
    hombre: false,
    mujer: true,
    niño: false,
    populares: true,
  },
  {
    id: 40,
    name: "Campera de Plumas Varilite Negra",
    price: "$30.499",
    img: ".img/mujer/40.jpg",
    description: "Mujer Casual",
    hombre: false,
    mujer: true,
    niño: false,
    populares: false,
  },

  // Sección Niños

  {
    id: 41,
    name: "Botines Copa Campo Firme",
    price: "$15.799",
    img: ".img/Niños/41",
    description: "Ñinos Fútbol",
    hombre: false,
    mujer: false,
    niño: true,
    populares: false,
  },

  {
    id: 42,
    name: "Botines Classic Grises",
    price: "$12.799",
    img: ".img/Niños/42",
    description: "Ñinos Fútbol",
    hombre: false,
    mujer: false,
    niño: true,
    populares: false,
  },

  {
    id: 43,
    name: "Buzo Adidas x Lego Amarillo ",
    price: "$10.999",
    img: ".img/Niños/43",
    description: "Ñinos Casual",
    hombre: false,
    mujer: false,
    niño: true,
    populares: true,
  },

  {
    id: 44,
    name: "Camiseta River Plate",
    price: "$10.000",
    img: ".img/Niños/44",
    description: "Ñinos Fútbol",
    hombre: false,
    mujer: false,
    niño: true,
    populares: false,
  },
  {
    id: 45,
    name: "Campera Negra con Gris",
    price: "$8.599",
    img: ".img/Niños/41",
    description: "Ñinos Casual",
    hombre: false,
    mujer: false,
    niño: true,
    populares: false,
  },
  {
    id: 46,
    name: "Conjunto Niña Disney Minnie",
    price: "$12.999",
    img: ".img/Niños/46",
    description: "Ñinos Conjuntos",
    hombre: false,
    mujer: false,
    niño: true,
    populares: false,
  },
  {
    id: 47,
    name: "Rompeviento Verde ",
    price: "$9.199",
    img: ".img/Niños/47",
    description: "Ñinos Casual",
    hombre: false,
    mujer: false,
    niño: true,
    populares: false,
  },
  {
    id: 48,
    name: "Ojotas Swim",
    price: "$4.999",
    img: ".img/Niños/48",
    description: "Ñinos Playa",
    hombre: false,
    mujer: false,
    niño: true,
    populares: false,
  },
  {
    id: 49,
    name: "Zapatillas Stan Smith Blancas",
    price: "$17.999",
    img: ".img/Niños/49",
    description: "Ñinos Zapatillas",
    hombre: false,
    mujer: false,
    niño: true,
    populares: false,
  },
  {
    id: 50,
    name: "Short River Plate",
    price: "$3.499",
    img: ".img/Niños/50",
    description: "Ñinos Fútbol",
    hombre: false,
    mujer: false,
    niño: true,
    populares: false,
  },
  {
    id: 51,
    name: "Short Negros Playa",
    price: "$3.999",
    img: ".img/Niños/51",
    description: "Ñinos Playa",
    hombre: false,
    mujer: false,
    niño: true,
    populares: false,
  },
  {
    id: 52,
    name: "Conjunto Niña Blanco y Rosado",
    price: "$12.499",
    img: ".img/Niños/52",
    description: "Ñinos Casual",
    hombre: false,
    mujer: false,
    niño: true,
    populares: false,
  },
  {
    id: 53,
    name: "Short Crema",
    price: "$2.999",
    img: ".img/Niños/53",
    description: "Ñinos Casual",
    hombre: false,
    mujer: false,
    niño: true,
    populares: false,
  },
  {
    id: 54,
    name: "Short Playa Negro y Azul",
    price: "$4.899",
    img: "img/Niños/54",
    description: "Ñinos Playa",
    hombre: false,
    mujer: false,
    niño: true,
    populares: false,
  },
  {
    id: 55,
    name: "Zapatillas SuperStar Blancas con Abroche",
    price: "$15.999",
    img: ".img/Niños/55",
    description: "Ñinos Zapatillas",
    hombre: false,
    mujer: false,
    niño: true,
    populares: false,
  },
  {
    id: 56,
    name: "Traje de Baño Enterizo",
    price: "$7.399",
    img: ".img/Niños/56",
    description: "Ñinos Playa",
    hombre: false,
    mujer: false,
    niño: true,
    populares: false,
  },
  {
    id: 57,
    name: "Remera Floreada",
    price: "$5.899",
    img: ".img/Niños/57",
    description: "Ñinos Casual",
    hombre: false,
    mujer: false,
    niño: true,
    populares: false,
  },
  {
    id: 58,
    name: "Zapatillas Nmd Croos x Lego",
    price: "$19.999",
    img: "img/Niños/58",
    description: "Ñinos Zapatillas",
    hombre: false,
    mujer: false,
    niño: true,
    populares: false,
  },
  {
    id: 59,
    name: "Remera Estampada Blanca Clasica",
    price: "$4.999",
    img: ".img/Niños/59",
    description: "Ñinos Casual",
    hombre: false,
    mujer: false,
    niño: true,
    populares: true,
  },
  {
    id: 60,
    name: "Remera Estampada Spiderman Negra",
    price: "$4.599",
    img: ".img/Niños/60",
    description: "Ñinos Casual",
    hombre: false,
    mujer: false,
    niño: true,
    populares: false,
  },
];
